name: DAST Security Scan - OWASP ZAP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Docker
        run: docker --version

      - name: Build and start app
        run: |
          docker build -t dast-practice-app .
          docker run -d -p 8000:8000 --name my-app dast-practice-app

      - name: Wait for app to be ready
        run: |
          echo "Esperando que la app inicie..."
          sleep 10
          curl http://localhost:8000/health

      - name: Pull OWASP ZAP Docker image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p ${{ github.workspace }}/zap-reports
          chmod 777 ${{ github.workspace }}/zap-reports
          docker run --network="host" \
            -v ${{ github.workspace }}/zap-reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8000 \
            -r zap-report.html \
            -I
        continue-on-error: true

      - name: List report files (debug)
        if: always()
        run: ls -la ${{ github.workspace }}/zap-reports/

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-security-report
          path: ${{ github.workspace }}/zap-reports/zap-report.html
